[package]
name = "use-text"
publish = true
version = "0.2.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
rust-version.workspace = true
description = "Composable text primitives for RustUse."
documentation = "https://docs.rs/use-text"
keywords = ["text", "string", "slug", "token", "line"]
categories = ["text-processing"]

[dependencies]
use-case.workspace = true
use-markdown.workspace = true
use-slug.workspace = true
use-text-line.workspace = true
use-token.workspace = true
use-word.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
