[package]
name = "use-line"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
rust-version.workspace = true
description = "Composable line-level text primitives for RustUse."

[lints]
workspace = true
